dbt_learn_repos:
  outputs:
    dev:
      account: PWYYCNX-IOB43524
      database: dbtlearn
      password: Sandeshpranjali@178
      role: ACCOUNTADMIN
      schema: public
      threads: 4
      type: snowflake
      user: PRANJALINAGARKAR
      warehouse: COMPUTE_WH
  target: dev